In [32]:
import pandas as pd
import numpy as np

 

In [33]:
df = pd.read_csv('height-weight.csv')


In [34]:
df.head()


Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [35]:
x = df[['Weight']]
y = df['Height']


In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [38]:
scaler.fit_transform(x)


array([[-1.64913128],
       [-0.90540541],
       [-1.47750223],
       [-0.79098604],
       [-0.21888922],
       [ 0.23878824],
       [ 0.3532076 ],
       [ 0.92530443],
       [ 1.21135284],
       [ 0.23878824],
       [ 0.46762697],
       [ 1.21135284],
       [ 1.78344966],
       [ 1.49740125],
       [ 0.63925602],
       [ 0.23878824],
       [-1.36308287],
       [-0.50493763],
       [ 0.12436887],
       [ 0.75367538],
       [-1.64913128],
       [-1.01982477],
       [-0.10446985]])

In [ ]:
scaler.mean_


array([73.82608696])

In [ ]:
scaler.scale_


array([17.47955868])